"""+ OrderContent ondelete CASCADE

Revision ID: 0c084bb13c08
Revises: 
Create Date: 2023-01-26 22:01:25.171555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c084bb13c08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_content', schema=None) as batch_op:
        batch_op.drop_constraint('fk_order_content_order_id_order', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_order_content_order_id_order'), 'order', ['order_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_content', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_order_content_order_id_order'), type_='foreignkey')
        batch_op.create_foreign_key('fk_order_content_order_id_order', 'order', ['order_id'], ['id'])

    # ### end Alembic commands ###
