"""+ Order

Revision ID: 5432f20e77de
Revises: 1b7d25e1d1f7
Create Date: 2023-01-20 01:15:47.361539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5432f20e77de'
down_revision = '1b7d25e1d1f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sum', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('sum')
        batch_op.drop_column('content')

    # ### end Alembic commands ###
