"""+ OrderContent ondelete CASCADE

Revision ID: decf6000f774
Revises: 0c084bb13c08
Create Date: 2023-01-27 02:53:22.744746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'decf6000f774'
down_revision = '0c084bb13c08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_id', sa.Integer(), nullable=True))
        batch_op.drop_column('filter')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filter', sa.INTEGER(), nullable=True))
        batch_op.drop_column('artist_id')

    # ### end Alembic commands ###
